//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTrafficControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Licenses = new HashSet<License>();
        }
    
        public int Id { get; set; }
        public string CommercialName { get; set; }
        public Nullable<int> CommercialNo { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string EmployerName { get; set; }
    
        public virtual ICollection<License> Licenses { get; set; }
    }
}
