//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTrafficControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convention
    {
        public Convention()
        {
            this.ConventionDocuments = new HashSet<ConventionDocument>();
            this.ConventionStages = new HashSet<ConventionStage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ConventionTypeId { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> ConventionDate { get; set; }
        public Nullable<int> StatesId { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<ConventionDocument> ConventionDocuments { get; set; }
        public virtual ICollection<ConventionStage> ConventionStages { get; set; }
        public virtual ConventionType ConventionType { get; set; }
    }
}
