//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTrafficControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public License()
        {
            this.PaymentReceipts = new HashSet<PaymentReceipt>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LicensesTypeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CenterId { get; set; }
        public string Statement { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Centre Centre { get; set; }
        public virtual Company Company { get; set; }
        public virtual LicensesType LicensesType { get; set; }
        public virtual ICollection<PaymentReceipt> PaymentReceipts { get; set; }
    }
}
