//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTrafficControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicensesType
    {
        public LicensesType()
        {
            this.Licenses = new HashSet<License>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Statement { get; set; }
    
        public virtual ICollection<License> Licenses { get; set; }
    }
}
