//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirTrafficControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReceipt
    {
        public int Id { get; set; }
        public Nullable<int> LicensesId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Stamp { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string PaymentReceiptPath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual License License { get; set; }
    }
}
